version: "3"

services:
  django_topograph:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - pg
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_topograph
  pg:
    image: postgres # use latest official postgres version
    container_name: topograph
    environment:
      POSTGRES_DB: topograph
      POSTGRES_USER: app
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  pg_data:
  static:



