"""Create Edge Model

Revision ID: b1355c4e88f9
Revises: 
Create Date: 2022-03-16 11:03:07.450703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1355c4e88f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_a', sa.String(), nullable=False),
    sa.Column('node_b', sa.String(), nullable=False),
    sa.Column('cost', sa.String(), nullable=False),
    sa.Column('meta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    # ### end Alembic commands ###
